CREATE TABLE IF NOT EXISTS vp_sync_state (
    source VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
    last_id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
